Conform to Home Assistant Discovery Spec
technyon/nuki_hub pull request #475
Opened 2024-09-20 17:13 UTC by ccutrer

## Description:

`availability` is documented as a list (of objects), not a single object. Just use the simpler availability_topic instead.

Fixes https://github.com/openhab/openhab-addons/issues/17375

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

2024-09-21 23:41 UTC, alexdelprete commented
The implementation perfectly conforms to HA [documentation](https://www.home-assistant.io/integrations/mqtt/#availability). A one item list **is** a list.

This is the code right now:

```c
 json["avty"]["t"] = _lockPath + mqtt_topic_mqtt_connection_state;
```

and it generates the following json in the `config` topic:

```json
  "avty": {
    "t": "~/maintenance/mqttConnectionState"
  },
```

in yaml config format it's equivalent to:

```yaml
mqtt:
  - lock:
      name: Door
      availability:
        - topic: "~/maintenance/mqttConnectionState"
```

as you can see, `avty` is a list, and `t` is the first string object of that list, so perfectly conformant to the documentation, and in fact Home Assistant perfectly recognizes the availability of the lock (it would throw errors otherwise).

There are many examples in HA docs with that one item example. I'd suggest you correct the openhab parser instead, because if it throws an error, it's not conformant to HA documentation.

2024-09-22 00:01 UTC, ccutrer commented
Respectfully, that is _not_ the equivalent yaml (example written in Python, since Home Assistant is Python, and the reference implementation):

```python
#!/usr/bin/env python3

import json
import yaml

# Sample JSON string
json_string = '''
{
  "avty": {
    "t": "~/maintenance/mqttConnectionState"
  }
}
'''

# Parse the JSON string
data = json.loads(json_string)

# Convert to YAML
yaml_output = yaml.dump(data, default_flow_style=False)

# Print the YAML output
print(yaml_output)
```

Output:
```yaml
avty:
  t: ~/maintenance/mqttConnectionState
```

Notice that there is no `-` before the `t`? The `-` introduces a list. Without, it's simply an object. I agree a list of a single item is still a list, but the JSON produced by nuki_hub is _not_ a list (technically called an array in JavaScript, and a sequence in YAML; it's Python that calls it a list), it's simply an object. Which I've not seen an _example_ of in the Home Assistant documentation - can you point me towards one? I'll also see if I can dig through Home Assistant's source to see if/where it treats the full `availability` object as a single object or a list.

2024-09-22 00:22 UTC, ccutrer commented
https://github.com/home-assistant/core/blob/97d0d91d2c464a7a8474e6035969116b70631e65/homeassistant/components/mqtt/discovery.py#L147

I'm pretty sure that `cv.ensure_list` wraps a non-list inside a list, so that it doesn't have to care about if it's a list or not.

2024-09-22 00:36 UTC, ccutrer commented
Feel free to close this if you feel that strongly about a single line change. I plan on updating openHAB to accept a non-list. It would still be nice if you could accept this change to get @adielsa going right away (I suspect your project is more agile at releases than openHAB). I'll also see if I can get a PR accepted to HA's documentation to clarify that an immediate object rather than a list is also acceptable. I've had good luck with similar clarifying PRs in the past, but this one will be a bit bigger since it's something repeated across all MQTT components.

Alternately, @adielsa, perhaps you could compile your own image of nuki_hub, with this PR, to get yourself going right away? I haven't looked too much into this project beyond finding its discovery code, so I'm not sure if compiling it yourself is common.

2024-09-22 03:07 UTC, alexdelprete requested changes
I'd modify like this:
```cpp
json["avty"][0]["t"] = availabilityTopic;
```

2024-09-22 03:44 UTC, alexdelprete commented
I found another small bug a few lines after the availability topic line. Closing this in favor of #476.

Thanks for the heads-up.

2024-09-22 03:44 UTC, closed without merging

2024-09-22 03:47 UTC, ccutrer commented
👍 

I appreciate the discussion. I’m always glad when we can improve compatibility and ease-of-use for users of _any_ home automation platform.

2024-09-22 04:04 UTC, technyon commented
#476 is merged

2024-09-22 05:07 UTC, alexdelprete commented
> I appreciate the discussion.

I did too. And sorry for the initial misunderstanding.